runtime: nodejs20
service: default

# Jika ada server Node.js (Express.js)
entrypoint: npm start

handlers:
  # Serve static files (HTML/CSS/JS)
  - url: /(.*\.(html|css|js|png|ico))$
    static_files: \1
    upload: (.*\.(html|css|js|png|ico))$

  # Arahkan semua rute ke index.html (jika SPA)
  - url: /.*
    static_files: index.html
    upload: index.html