substitutions: 
 _ENV: gs://h-03-451207.appspot.com/notes/.env

steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_ENV}", "backend/.env"]
    
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/tcc-be", "-f", "backend/Dockerfile", "backend"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/tcc-be"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run", "deploy", "be",
        "--image", "gcr.io/$PROJECT_ID/tcc-be",
        "--port", "5000",
        "--region", "asia-southeast1",  # Ganti region jika perlu
        "--allow-unauthenticated",
        "--platform", "managed",
        "--timeout", "3600s",  # Timeout lebih panjang
        "--cpu", "1",
        "--memory", "1Gi",  # Naikkan memory
        "--set-env-vars", "NODE_ENV=production"
      ]
options:
  logging: CLOUD_LOGGING_ONLY