steps:
  # Build Docker image (dengan konteks build di folder backend)
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/tcc-be", "-f", "Dockerfile.be", "."]
    dir: "backend"  # Pastikan build dilakukan dalam folder backend

  # Push Docker image ke Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/tcc-be"]

  # Deploy ke Cloud Run dengan penyesuaian environment
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run", "deploy", "tcc-be-service",  # Nama service yang lebih deskriptif
        "--image", "gcr.io/$PROJECT_ID/tcc-be",
        "--platform", "managed",
        "--region", "us-central1",
        "--port", "8080",  # Sesuai EXPOSE di Dockerfile
        "--timeout", "3600",  # Timeout maksimum (1 jam)
        "--cpu", "1",  # Alokasi CPU
        "--memory", "512Mi",  # Alokasi memori
        "--allow-unauthenticated",
        "--set-env-vars", "NODE_ENV=production",
        "--vpc-connector", "projects/$PROJECT_ID/locations/us-central1/connectors/[CONNECTOR_NAME]",  # Jika menggunakan VPC
        "--ingress", "all"  # Atur sesuai kebutuhan keamanan
      ]

# Opsi tambahan
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"  # Untuk build yang lebih cepat
  diskSizeGb: 100  # Ukuran disk yang cukup

# Definisikan artifact hasil build
images: ["gcr.io/$PROJECT_ID/tcc-be"]