steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/tcc-be", "-f", "Dockerfile", "."]
    dir: "backend"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/tcc-be"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run", "deploy", "be",
        "--image", "gcr.io/$PROJECT_ID/tcc-be",
        "--port", "5000",  # Port aplikasi (tanpa set PORT env)
        "--region", "asia-southeast1",
        "--allow-unauthenticated",
        "--platform", "managed",
        "--cpu", "1",
        "--memory", "512Mi",
        "--timeout", "3600"
      ]

options:
  logging: CLOUD_LOGGING_ONLY